default: all

CC = arm-linux-gnueabihf-g++
LINK_TARGET = $(OBJ_DIR)blinky
DEPEND_OPTS = -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)"
SRC_DIR = ./src/
OBJ_DIR = ./obj/
OBJS = \
	$(OBJ_DIR)delay.o \
	$(OBJ_DIR)blinky.o \
	$(OBJ_DIR)main.o
############################
# List of dependency files
C_DEPS = \
  $(OBJ_DIR)delay.d \
  $(OBJ_DIR)blinky.d \
  $(OBJ_DIR)main.d

############################
# Include generated dependcy files (only if not clean target)
ifneq ($(MAKECMDGOALS),clean)
ifneq ($(strip $(C_DEPS)),)
-include $(C_DEPS)
endif
endif

all: $(LINK_TARGET)
	@echo All done!

clean:
	-@rm $(LINK_TARGET)
	-@rm $(OBJS)
	-@rm $(C_DEPS)
	@echo Clean done!

############################
# Pattern rule to compile a file	
# $@ matches the target
# $< matches the first dependent
$(OBJ_DIR)%.o: $(SRC_DIR)%.c
	$(CC) $(DEPEND_OPTS) -g3 -c "$<" -o "$@" 

$(LINK_TARGET): $(OBJS)
#	$(CC) $(OBJS) -pthread -lwiringPi -lcrypt -lm -lrt -o $@
	$(CC) $(OBJS) -ggdb -lwiringPi -o $@
